# Generated by Django 4.2.7 on 2023-11-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketchup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KetchupEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=256)),
                ('maxMemberCount', models.IntegerField()),
                ('estimatedDuration', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
