# Generated by Django 4.2.7 on 2023-11-27 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketchup', '0002_ketchupevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketchupevent',
            name='estimatedDuration',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='ketchupevent',
            name='maxMemberCount',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
