# Generated by Django 4.2.7 on 2023-12-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketchup', '0004_ketchupevent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketchupevent',
            name='description',
            field=models.CharField(max_length=5120),
        ),
    ]
