# Generated by Django 4.2.7 on 2023-12-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketchup', '0010_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketchupevent',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
