# Generated by Django 4.2.7 on 2024-01-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketchup', '0011_alter_ketchupevent_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ketchupevent',
            name='interests',
            field=models.ManyToManyField(related_name='events', to='ketchup.interest'),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(related_name='interested_users', to='ketchup.interest'),
        ),
    ]
