# Generated by Django 4.2.7 on 2024-01-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketchup', '0014_businessprofile_user_role_delete_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
