# Generated by Django 4.2.7 on 2024-01-21 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ketchup', '0015_alter_businessprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='ketchup.ketchupevent'),
        ),
    ]
