# Generated by Django 4.2.7 on 2024-01-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketchup', '0017_businessprofile_image_businessprofile_opening_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_level',
            field=models.CharField(choices=[('private', 'Private'), ('openToGroup', 'Open to Group'), ('public', 'Public')], default='private', max_length=12),
        ),
    ]
