# Generated by Django 4.2.7 on 2024-02-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketchup', '0020_businessprofile_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='address',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
