# Generated by Django 4.2.7 on 2024-02-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketchup', '0021_alter_businessprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
