# Generated by Django 4.2.7 on 2024-02-21 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ketchup', '0022_alter_businessprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ketchupevent',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_of_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ketchupevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to=settings.AUTH_USER_MODEL),
        ),
    ]
