# Generated by Django 4.2.7 on 2024-03-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketchup', '0024_ketchupevent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketchupevent',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ketchupevent',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ketchupevent',
            name='description',
            field=models.CharField(max_length=5120, null=True),
        ),
    ]
