# Generated by Django 4.2.7 on 2024-03-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketchup', '0025_alter_ketchupevent_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ketchupevent',
            name='category',
        ),
        migrations.AlterField(
            model_name='ketchupevent',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ketchupevent',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ketchupevent',
            name='description',
            field=models.CharField(blank=True, default='', max_length=5120, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=5120, null=True),
        ),
    ]
